# Deployment YAML for H100 GPU
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: qwen--qwen3-5-0-8b-vllm
endpoint_name: qwen--qwen3-5-0-8b-h100
model: azureml://registries/mabables-reg-feb26/models/qwen--qwen3-5-0-8b/versions/50
instance_type: Standard_NC40ads_H100_v5
instance_count: 1
