$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: vllm-qwen--qwen3-5-0-8b
version: 50
build:
  path: docker
  dockerfile_path: Dockerfile
description: "vLLM inference server for Qwen/Qwen3.5-0.8B"
tags:
  framework: vllm
  hf_model_id: Qwen/Qwen3.5-0.8B
