apply_library_patches: true
base_image: null
bis_llm: null
build:
  arguments: {}
  model_server: TrussServer
  no_cache: false
  secret_to_path_mapping: {}
build_commands: []
bundled_packages_dir: packages
cache_internal: []
data_dir: data
description: null
docker_server: null
environment_variables:
  HF_HUB_OFFLINE: '1'
  MODEL_WEIGHTS_PATH: /app/model-weights
  TRANSFORMERS_OFFLINE: '1'
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
input_type: Any
live_reload: false
model_cache: []
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: qwen3-5-0-8b
model_type: Model
python_version: py311
requirements:
- torch==2.4.1
- transformers==4.44.2
- accelerate==0.33.0
- safetensors==0.4.4
requirements_file: null
resources:
  accelerator: A100
  cpu: '4'
  memory: 16Gi
  use_gpu: true
runtime:
  egress_restrictions: null
  enable_debug_logs: false
  enable_tracing_data: false
  health_checks:
    restart_check_delay_seconds: null
    restart_threshold_seconds: null
    startup_threshold_seconds: null
    stop_traffic_threshold_seconds: null
  is_websocket_endpoint: false
  predict_concurrency: 1
  remote_ssh:
    enabled: false
  streaming_read_timeout: 60
  transport:
    kind: http
  truss_server_version_override: null
secrets: {}
spec_version: '2.0'
system_packages: []
training_checkpoints: null
trt_llm: null
use_local_src: false
weights: []
